version: '3.8'

services:
  server:
    image: mockingbird:latest
    build: .
    volumes:
      - ./datasets:/datasets
      - ./ckpt/synthesizer/saved_models:/workspace/data/ckpt/synthesizer/saved_models
      - ./ckpt/ppg_extractor:/workspace/data/ckpt/ppg_extractor
      - ./ckpt/ppg2mel:/workspace/data/ckpt/ppg2mel
    environment:
      - DATASET_MIRROR=US
      - FORCE_RETRAIN=false
      - TRAIN_DATASETS=aidatatang_200zh magicdata aishell3 data_aishell
      - TRAIN_SKIP_EXISTING=true
    ports:
      - 8080:8080
#    deploy:
#      resources:
#        reservations:
#          devices:
#            - driver: nvidia
#              device_ids: [ '0' ]
#              capabilities: [ gpu ]
